site_name: 岩溶尘的空间
site_url: https://blog.yrc-bot.xyz
repo_url: https://github.com/yrc-better/yrc-blog

theme:
  name: material
  language: zh

plugins:
  - search:
      lang: zh
  - mkdocs-jupyter:
      execute: true
      include_source: true

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - 首页: index.md
  - 实验:
      - 实验 001:正弦曲线与直方图: experiments/exp-001.ipynb
      # - 实验 002：xxx: experiments/exp-002.ipynb
  - 博文:
      - 2025-08-14:我的第一篇文章: posts/2025-08-14-first-post.md
  - Python 示例: python-demo.ipynb   # 若有


