site_name: 岩溶尘的空间
site_url: https://blog.yrc-bot.xyz
repo_url: https://github.com/yrc-better/yrc-blog

theme:
  name: material
  language: zh
  features:
    - content.code.copy
    - content.tabs.link
  #  - navigation.instant
  custom_dir: overrides

plugins:
  - search:
      lang: zh
# - markdown-exec
  - mkdocs-jupyter:
      execute: true
      include_source: true
  

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


markdown_extensions:
  - md_in_html
  - admonition
  - attr_list
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true






nav:
  - 首页: index.md
  - 实验:
      - 实验 001:正弦曲线与直方图: experiments/exp-001.ipynb
      - 实验 002:xxx: experiments/exp-002.ipynb
      - "PyScript Demo": labs/pyscript-demo.md
  - 博文:
      - 复旦江湾研0租房经验: posts/复旦江湾研0租房经验.md
      - 人工智能导论学习笔记1: posts/李宏毅人工智能导论学习笔记(一).md
      - 人工智能导论学习笔记2: posts/李宏毅人工智能导论学习笔记(二).md
      - 人工智能导论学习笔记3: posts/李宏毅人工智能导论学习笔记(三).md
      - 人工智能导论学习笔记4: posts/李宏毅人工智能导论学习笔记(四).md
  - Python 示例: python-demo.ipynb   # 若有


