site_name: 岩溶尘的空间
site_url: https://blog.yrc-bot.xyz
repo_url: https://github.com/yrc-better/yrc-blog

theme:
  name: material
  language: zh

plugins:
  - search:
      lang: zh
  - mkdocs-jupyter:
      execute: true
      include_source: true

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - 首页: index.md
  - Python 示例: python-demo.ipynb

