name: Deploy MkDocs

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'   # 指定一个稳定的小版本
          cache: 'pip'             # 可选：启用 pip 缓存，加速安装

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # 如果你在站点里用到了 jieba(看日志里有)，也可以一起放到 requirements.txt
          # 或者单独安装：
          # pip install jieba

      # 如果你不想把警告当失败，可以去掉 --strict
      - name: Build site
        run: mkdocs build --clean --strict

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          cname: blog.yrc-bot.xyz
